MockWebApp/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockClassLibrary.Models;
using MockExamConsoleApp.Data;

namespace MockWebApp.Controllers
{
    public class FlightsController : Controller
    {
        private readonly FlightContext _context;

        public FlightsController(FlightContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index()
        {
            return View(await _context.Flights.ToListAsync());
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flights = await _context.Flights
                .Include(p => p.Bookings)
                .ThenInclude(p => p.Passenger)
                .FirstOrDefaultAsync(m => m.FlightID == id);
            if (flights == null)
            {
                return NotFound();
            }

            return View(flights);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FlightID,FlightNumber,DepartureDate,Origin,Destination,Country,MaxSeats")] Flights flights)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flights);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flights);
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flights = await _context.Flights.FindAsync(id);
            if (flights == null)
            {
                return NotFound();
            }
            return View(flights);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlightID,FlightNumber,DepartureDate,Origin,Destination,Country,MaxSeats")] Flights flights)
        {
            if (id != flights.FlightID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flights);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightsExists(flights.FlightID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flights);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flights = await _context.Flights
                .FirstOrDefaultAsync(m => m.FlightID == id);
            if (flights == null)
            {
                return NotFound();
            }

            return View(flights);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flights = await _context.Flights.FindAsync(id);
            if (flights != null)
            {
                _context.Flights.Remove(flights);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightsExists(int id)
        {
            return _context.Flights.Any(e => e.FlightID == id);
        }
    }
}

MockWebApp/Controllers/PassengersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockClassLibrary.Models;
using MockExamConsoleApp.Data;

namespace MockWebApp.Controllers
{
    public class PassengersController : Controller
    {
        private readonly FlightContext _context;

        public PassengersController(FlightContext context)
        {
            _context = context;
        }

        // GET: Passengers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Passengers
                .Include(p => p.Bookings)
                .ToListAsync());

        }

        // GET: Passengers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengers = await _context.Passengers
                .Include(p => p.Bookings)
                .ThenInclude(p => p.Flight)
                .FirstOrDefaultAsync(m => m.PassengerID == id);

            if (passengers == null)
            {
                return NotFound();
            }

            return View(passengers);
        }

        // GET: Passengers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Passengers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PassengerID,Name,PassportNumber")] Passengers passengers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(passengers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(passengers);
        }

        // GET: Passengers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengers = await _context.Passengers.FindAsync(id);
            if (passengers == null)
            {
                return NotFound();
            }
            return View(passengers);
        }

        // POST: Passengers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PassengerID,Name,PassportNumber")] Passengers passengers)
        {
            if (id != passengers.PassengerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(passengers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PassengersExists(passengers.PassengerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(passengers);
        }

        // GET: Passengers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passengers = await _context.Passengers
                .FirstOrDefaultAsync(m => m.PassengerID == id);
            if (passengers == null)
            {
                return NotFound();
            }

            return View(passengers);
        }

        // POST: Passengers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var passengers = await _context.Passengers.FindAsync(id);
            if (passengers != null)
            {
                _context.Passengers.Remove(passengers);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PassengersExists(int id)
        {
            return _context.Passengers.Any(e => e.PassengerID == id);
        }
    }
}

MockWebApp/Views/Passengers/Create.cshtml
@model MockClassLibrary.Models.Passengers

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Passengers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportNumber" class="control-label"></label>
                <input asp-for="PassportNumber" class="form-control" />
                <span asp-validation-for="PassportNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockWebApp/Views/Passengers/Delete.cshtml
@model MockClassLibrary.Models.Passengers

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Passengers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassportNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassportNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PassengerID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MockWebApp/Views/Passengers/Details.cshtml
@model MockClassLibrary.Models.Passengers
@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Passengers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassportNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassportNumber)
        </dd>
    </dl>
</div>
<br />
@await Html.PartialAsync("_FlightList", Model.Bookings)
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PassengerID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MockWebApp/Views/Passengers/Edit.cshtml
@model MockClassLibrary.Models.Passengers

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Passengers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PassengerID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportNumber" class="control-label"></label>
                <input asp-for="PassportNumber" class="form-control" />
                <span asp-validation-for="PassportNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockWebApp/Views/Passengers/Index.cshtml
@model IEnumerable<MockClassLibrary.Models.Passengers>
@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassportNumber)
            </th>
            <th>
                Total Spent
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var totalSpent = item.Bookings?.Sum(b => b.TicketCost + b.BaggageCharge) ?? 0;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PassportNumber)
                </td>
                <td>
                    €@totalSpent.ToString("F2")
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PassengerID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.PassengerID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.PassengerID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MockWebApp/Views/Passengers/_FlightList.cshtml
@model IEnumerable<MockClassLibrary.Models.Bookings>
<div class="card">
    <div class="card-header">
        <h4>Flights</h4>
    </div>
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Flight ID</th>
                    <th>Flight Number</th>
                    <th>Departure Date</th>
                    <th>Origin</th>
                    <th>Destination</th>
                    <th>Country</th>
                    <th>Max Seats</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var booking in Model)
                {
                    <tr>
                        <td>@booking.Flight.FlightID</td>
                        <td>@booking.Flight.FlightNumber</td>
                        <td>@booking.Flight.DepartureDate</td>
                        <td>@booking.Flight.Origin</td>
                        <td>@booking.Flight.Destination</td>
                        <td>@booking.Flight.Country</td>
                        <td>@booking.Flight.MaxSeats</td>
                        <td>
                            <a asp-controller="Flights"
                               asp-action="Details"
                               asp-route-id="@booking.FlightID">
                                View Flight
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>